[project]
name = "home-server"
version = "0.1.0"
description = "Modular H.O.M.E. automation backend"
readme = "README.md"
requires-python = "==3.13.*"
license = {text = "MIT"}
authors = [
    { name = "Arpad Szabo", email = "arpad2000@gmail.com" }
]

dependencies = [
    "fastapi>=0.121.2",
    "pydantic>=2.12.4",
    "uvicorn[standard]>=0.38.0",
]


[tool.setuptools.packages.find]
include = ["app"]

# ---- UV CONFIG ----
[tool.uv]
package = true

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
    "pyright>=1.1.407",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.6",
    "safety>=3.7.0",
]


###############################################
#                 RUFF CONFIG                 #
###############################################

[tool.ruff]
preview = true
target-version = "py313"
line-length = 100
exclude = [
    ".vscode",
    ".git",
    ".github",
    ".venv",
    "venv",
    "__pycache__",
    "migrations",
    ".pytest_cache",
    ".ruff_cache",
]

[tool.ruff.lint]
select = [
    "F",     # Pyflakes
    "E","W", # Pycodestyle
    "N",     # Pep8-naming
    "I",     # isort
    "A",     # flake8-builtins
    "UP",    # pyupgrade

    "B",     # Bugbear
    "S",     # flake8-bandit
    "TRY",   # tryceratops

    "SIM",   # flake8-simplify
    "RET",   # flake8-return
    "ARG",   # flake8-unused-arguments
    "DTZ",   # flake8-datetimez
    "DOC",   # pydoclint
    "RUF",   # Ruff-specific
]

ignore = [
    "E501",   # Ruff formatter & readability handles long lines
    "S101",   # Allow assert (useful in tests)
    "ARG002", # FastAPI dependency injection pattern
]

[tool.pydoclint]
style = "google"
ignore-private = true
ignore = [
  "missing-module-docstring",
  "missing-package-docstring",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
