"""add cleared_at to shopping items

A bought item now stays on the list, dimmed, until the household clears it.
`cleared_at` records that. No backfill: every item bought before this change
becomes visible-but-bought, which is the new intended state, and one tap on
"clear bought" tidies them. Purchases are untouched.

Revision ID: 2adfd2692d1c
Revises: bedfd61a15a3
Create Date: 2026-09-11 16:02:37.406817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adfd2692d1c'
down_revision: Union[str, Sequence[str], None] = 'bedfd61a15a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_items', sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_items', 'cleared_at')
    # ### end Alembic commands ###
