"""create shopping list schema

Revision ID: 3d5b438d432f
Revises: 
Create Date: 2026-09-10 18:48:04.383395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5b438d432f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shopping_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Float(), server_default=sa.text('1'), nullable=False),
    sa.Column('unit', sa.String(length=10), server_default=sa.text("'piece'"), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('origin', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_shopping_items_name_not_blank'),
    sa.CheckConstraint("origin IN ('manual', 'recipe')", name='ck_shopping_items_origin_known'),
    sa.CheckConstraint("unit IN ('piece', 'box', 'kg', 'g', 'l', 'dl', 'm', 'cm')", name='ck_shopping_items_unit_known'),
    sa.CheckConstraint('quantity > 0', name='ck_shopping_items_quantity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_stores_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_stores_name_lower', 'stores', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('shopping_item_purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('bought_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shopping_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['household_members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('shopping_item_stores',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shopping_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id', 'store_id')
    )
    op.create_index('ix_shopping_item_stores_store_id', 'shopping_item_stores', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopping_item_stores_store_id', table_name='shopping_item_stores')
    op.drop_table('shopping_item_stores')
    op.drop_table('shopping_item_purchases')
    op.drop_index('ux_stores_name_lower', table_name='stores')
    op.drop_table('stores')
    op.drop_table('shopping_items')
    op.drop_table('household_members')
    # ### end Alembic commands ###
