"""add updated_at to shopping items

The editing client's time of the last applied edit, so that "later edit
wins" can be decided when a phone that was away syncs its queue. No
backfill: NULL means never edited, which loses to any edit — the right
answer for every existing row.

Revision ID: 3943516b1ed0
Revises: 2adfd2692d1c
Create Date: 2026-09-11 19:32:29.069586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3943516b1ed0'
down_revision: Union[str, Sequence[str], None] = '2adfd2692d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_items', 'updated_at')
    # ### end Alembic commands ###
