"""add categories and item catalogue

Adds the category registry and the item catalogue, links items to catalogue
entries, and BACKFILLS an entry for every distinct existing item name so that
nothing already on the household's list loses its identity.

The backfill is the first data-touching migration in this project. It only
ever inserts catalogue rows and sets a previously-null column; it never
changes an item's name, stores, dates or purchases, so the downgrade restores
`shopping_items` exactly by dropping the column again.

Revision ID: bedfd61a15a3
Revises: 3d5b438d432f
Create Date: 2026-09-11 14:09:19.518207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedfd61a15a3'
down_revision: Union[str, Sequence[str], None] = '3d5b438d432f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('colour', sa.String(length=7), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("btrim(icon) <> ''", name='ck_categories_icon_not_blank'),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_categories_name_not_blank'),
    sa.CheckConstraint("colour ~ '^#[0-9a-fA-F]{6}$'", name='ck_categories_colour_hex'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_categories_name_lower', 'categories', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('catalogue_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_catalogue_entries_name_not_blank'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_catalogue_entries_name_lower', 'catalogue_entries', [sa.literal_column('lower(name)')], unique=True, postgresql_ops={'lower(name)': 'text_pattern_ops'})
    op.create_table('catalogue_entry_stores',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['catalogue_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'store_id')
    )
    op.create_index('ix_catalogue_entry_stores_store_id', 'catalogue_entry_stores', ['store_id'], unique=False)
    op.add_column('shopping_items', sa.Column('catalogue_entry_id', sa.Uuid(), nullable=True))
    op.create_index('ix_shopping_items_catalogue_entry_id', 'shopping_items', ['catalogue_entry_id'], unique=False)
    op.create_foreign_key('fk_shopping_items_catalogue_entry_id', 'shopping_items', 'catalogue_entries', ['catalogue_entry_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    _backfill_catalogue_from_existing_items()


def _backfill_catalogue_from_existing_items() -> None:
    """Give every existing item a catalogue entry.

    One entry per distinct case-insensitive name. The entry takes the most
    recently used spelling and the newest item's creation time as
    `last_used_at`, so suggestions start ordered sensibly rather than all
    tying on the migration timestamp. Entries start with no remembered stores:
    guessing them from history would bake in whatever happened to be typed
    once, and a wrong prefill is worse than an empty one.
    """
    op.execute(
        sa.text(
            """
            INSERT INTO catalogue_entries (id, name, category_id, last_used_at)
            SELECT gen_random_uuid(), latest.name, NULL, latest.created_at
            FROM (
                SELECT DISTINCT ON (lower(name)) name, created_at
                FROM shopping_items
                ORDER BY lower(name), created_at DESC
            ) AS latest
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE shopping_items AS item
            SET catalogue_entry_id = entry.id
            FROM catalogue_entries AS entry
            WHERE lower(entry.name) = lower(item.name)
              AND item.catalogue_entry_id IS NULL
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shopping_items_catalogue_entry_id', 'shopping_items', type_='foreignkey')
    op.drop_index('ix_shopping_items_catalogue_entry_id', table_name='shopping_items')
    op.drop_column('shopping_items', 'catalogue_entry_id')
    op.drop_index('ix_catalogue_entry_stores_store_id', table_name='catalogue_entry_stores')
    op.drop_table('catalogue_entry_stores')
    op.drop_index('ux_catalogue_entries_name_lower', table_name='catalogue_entries', postgresql_ops={'lower(name)': 'text_pattern_ops'})
    op.drop_table('catalogue_entries')
    op.drop_index('ux_categories_name_lower', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
