name: Code Quality

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/code-quality.yml'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'backend/**'
      - '.github/workflows/code-quality.yml'

defaults:
  run:
    working-directory: backend

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: backend/uv.lock

      - name: Set up Python 3.14
        run: uv python install

      - name: Install project dependencies
        run: uv sync --locked

      ########################
      # Code checks
      ########################
      - name: Ruff - Formatting
        run: uv run ruff format --check app tests

      - name: Ruff - Static code analysis
        run: uv run ruff check app tests

      - name: Pyright - Type checking
        run: uv run pyright

      ########################
      # Tests and coverage
      ########################
      - name: Run tests
        run: uv run pytest --cov=app --cov-report=term-missing tests/
